"""Build the game's player/NPC spritesheet from the DALL-E-sourced office avatar
sprites in pixel-art/office-avatar-sprites/ (already chroma-keyed, pose-extracted,
and mask-generated by that folder's own build.py — this script only crops each
frame tightly to its content, rescales everything uniformly, and re-lays it out
into the layout DataX Town's game code expects).

Output: game/assets/avatars.png (+ avatars_hair_mask.png, avatars_clothing_mask.png,
avatars.json). Row 0-1 = generic male/female (player, freely recolorable). Rows 2+ =
bespoke per-exec designs already prepared for specific NPCs (see VARIANTS below) —
used as-is, no recolor. 16 cols per row (4 directions x 4 walk frames).

Recolor stays mask-based at runtime (game/js/avatar.js): white pixels in the hair/
clothing mask get replaced with a brightness-preserving remap toward the picked
color, so any hex the player picks works — not just a fixed palette of variants.
Run: python build_avatars.py
"""
import json
from collections import deque
from pathlib import Path
from PIL import Image, ImageFilter, ImageChops

OUT = Path(__file__).resolve().parent
SRC = OUT.parent.parent / "pixel-art" / "office-avatar-sprites"

SRC_FRAME = 128
SRC_COLS = SRC_ROWS = 4
# แถวต้นฉบับ (DALL-E) เรียง front,right,left,back — เกมใช้ down,left,right,up
# ต้องแม็พ index แถวต้นฉบับ -> ตำแหน่งคอลัมน์บล็อกที่จะเขียนออก
SRC_DIRS = ["front", "right", "left", "back"]
GAME_DIRS = ["down", "left", "right", "up"]
SRC_ROW_FOR_GAME_DIR = [SRC_DIRS.index(d if d != "down" else "front") if d != "up" else SRC_DIRS.index("back")
                        for d in GAME_DIRS]
# ชัดเจนกว่าใช้ list เขียนตรง ๆ:
SRC_ROW_FOR_GAME_DIR = [SRC_DIRS.index("front"), SRC_DIRS.index("left"),
                        SRC_DIRS.index("right"), SRC_DIRS.index("back")]

FW, FH = 32, 50          # เฟรมสุดท้ายในเกม (~2x ของตัวละครเดิม 16x24 — ใหญ่ขึ้นชัดเจนแต่ยังพอดีกับ tile 24px)
TARGET_H = 48              # เนื้อตัวละคร (ไม่รวมขอบ) สูงสุดที่ยอมให้สูง — เว้นขอบบนไว้เล็กน้อย
# แถวที่ 0-1 = ตัวผู้เล่น (ชาย/หญิง ทั่วไป ปรับสีผม/เสื้อได้อิสระ)
# แถวที่ 2+ = ดีไซน์เฉพาะของผู้บริหารแต่ละคน (ผู้ใช้เตรียม DALL-E มาให้ตรงตัวอยู่แล้ว ไม่ต้อง recolor)
VARIANTS = [
    ("male", "m", None), ("female", "f", None),
    ("male_ceo_v2", "m", "ceo"), ("female_cto_v2", "f", "cto"), ("male_cco_v2", "m", "cco"),
    ("male_cfo", "m", "cfo"), ("female_cdo_v2", "f", "cdo"), ("male_cro", "m", "cro"),
]


def content_bbox(frame_rgba):
    return frame_rgba.getchannel("A").getbbox()


def measure_uniform_scale():
    """หาสเกลเดียวที่ใช้กับทุกเฟรม/ทุก variant ไม่งั้นตัวละครจะดูขยับขนาดเป็นเฟรม ๆ ตอนเดิน"""
    max_w = max_h = 0
    for prefix, _, _ in VARIANTS:
        sheet = Image.open(SRC / f"{prefix}_spritesheet.png").convert("RGBA")
        for row in range(SRC_ROWS):
            for col in range(SRC_COLS):
                frame = sheet.crop((col * SRC_FRAME, row * SRC_FRAME, (col + 1) * SRC_FRAME, (row + 1) * SRC_FRAME))
                bbox = content_bbox(frame)
                if not bbox:
                    continue
                max_w = max(max_w, bbox[2] - bbox[0])
                max_h = max(max_h, bbox[3] - bbox[1])
    return TARGET_H / max_h, max_w, max_h


def resize_rgba_premultiplied(im, new_w, new_h):
    """LANCZOS บน RGBA ตรง ๆ (ไม่ premultiply) ทำให้ขอบภาพเกิดจุดสี noise/ringing เพราะพิกเซล
    โปร่งใส (RGB มักเป็น (0,0,0)) ไปปนกับสีขอบตอน resize — คูณ RGB ด้วยอัลฟาก่อน (premultiply)
    resize แล้วหารกลับ ถึงจะได้ขอบสะอาดแบบที่โปรแกรมวาดภาพทั่วไปทำ"""
    r, g, b, a = im.split()
    rgb = Image.merge("RGB", (r, g, b))
    black = Image.new("RGB", im.size, (0, 0, 0))
    premult = Image.composite(rgb, black, a)
    premult_resized = premult.resize((new_w, new_h), Image.LANCZOS)
    a_resized = a.resize((new_w, new_h), Image.LANCZOS)
    pr, pg, pb = premult_resized.split()
    a_arr = a_resized.load()
    pr_l, pg_l, pb_l = pr.load(), pg.load(), pb.load()
    out = Image.new("RGBA", (new_w, new_h))
    out_px = out.load()
    # ที่ alpha ต่ำมาก การหารกลับ (k = 255/av) ขยาย noise เล็ก ๆ ให้กลายเป็นสีจัดจ้านผิดเพี้ยน
    # (เช่น av=1 -> k=255 เท่า) ตัดพิกเซล alpha ต่ำกว่า threshold ทิ้งเป็นโปร่งใสสนิทไปเลยดีกว่า
    # เก็บไว้แบบโปร่งใสจาง ๆ ที่ไม่มีใครมองเห็นต่างกันอยู่แล้ว แต่ป้องกัน noise ได้เด็ดขาด
    ALPHA_CUTOFF = 40
    for y in range(new_h):
        for x in range(new_w):
            av = a_arr[x, y]
            if av < ALPHA_CUTOFF:
                out_px[x, y] = (0, 0, 0, 0)
            else:
                k = 255 / av
                out_px[x, y] = (min(255, round(pr_l[x, y] * k)), min(255, round(pg_l[x, y] * k)),
                                 min(255, round(pb_l[x, y] * k)), av)
    return out


def place(cropped, scale, mode):
    """ย่อ + วางกึ่งกลางแนวนอน ชิดขอบล่าง (เท้าแนบพื้นเฟรมพอดี) บนแคนวาสขนาด FW x FH"""
    w, h = cropped.size
    new_w, new_h = max(1, round(w * scale)), max(1, round(h * scale))
    if mode == "RGBA":
        resized = resize_rgba_premultiplied(cropped, new_w, new_h)
    else:
        resized = cropped.resize((new_w, new_h), Image.LANCZOS)
    canvas = Image.new(mode, (FW, FH), (0, 0, 0, 0) if mode == "RGBA" else 0)
    dx, dy = (FW - new_w) // 2, FH - new_h
    if mode == "RGBA":
        canvas.alpha_composite(resized, (dx, dy))
    else:
        canvas.paste(resized, (dx, dy))
    return canvas


def rebinarize_mask(mask_l):
    return mask_l.point(lambda v: 255 if v >= 96 else 0)


def drop_small_components(mask_l, min_ratio=0.2):
    """เก็บเฉพาะกลุ่มพิกเซล (มาสก์ต่อเนื่องกัน) ที่ใหญ่พอ ตัดจุดเล็ก ๆ ที่แยกจากตัวหลักทิ้ง —
    ต้นฉบับบางเฟรมมีเศษมาสก์เล็ก ๆ (เช่น เครื่องประดับผมสีคล้ายเสื้อ) หลุดมาด้วย ถ้าปล่อยไว้
    ตอน recolor จะกลายเป็นจุดสีผิดที่แปลกตาไปโผล่กลางหน้า/ผมโดยไม่เกี่ยวกับส่วนหลักเลย"""
    w, h = mask_l.size
    px = mask_l.load()
    seen = [[False] * w for _ in range(h)]
    comps = []
    for y0 in range(h):
        for x0 in range(w):
            if px[x0, y0] < 128 or seen[y0][x0]:
                continue
            q = deque([(x0, y0)]); seen[y0][x0] = True; pts = []
            while q:
                x, y = q.popleft(); pts.append((x, y))
                for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
                    if 0 <= nx < w and 0 <= ny < h and px[nx, ny] >= 128 and not seen[ny][nx]:
                        seen[ny][nx] = True; q.append((nx, ny))
            comps.append(pts)
    if not comps:
        return mask_l
    biggest = max(len(c) for c in comps)
    out = Image.new("L", (w, h), 0)
    outpx = out.load()
    for c in comps:
        if len(c) >= biggest * min_ratio:
            for x, y in c:
                outpx[x, y] = 255
    return out


# ชุดสไปรท์เฉพาะคน (ผู้บริหารแต่ละคน) หลายชุด แถวหน้า/หลัง (front/back) จาก DALL-E มีแค่ pose
# นิ่งซ้ำ ๆ ไม่มี walk cycle จริงแบบแถวข้าง (ซ้าย/ขวามีขาไขว้สลับชัดเจน แต่หน้า/หลังแทบนิ่งสนิท)
# เดินหันหน้า/หลังเลยดูเหมือนตัวละครลอยไม่เดิน — เสริมจังหวะเด้งขึ้นลงสังเคราะห์เองให้ดูเดินจริง
BOB_PATTERN = [0, -1, 0, 1]  # px ต่อเฟรม 0-3, ใช้เฉพาะทิศ down/up (game dir index 0, 3)


def build():
    scale, max_w, max_h = measure_uniform_scale()
    print(f"uniform scale {scale:.4f} (source max content {max_w}x{max_h})")

    total_cols = len(GAME_DIRS) * SRC_COLS
    out_sheet = Image.new("RGBA", (FW * total_cols, FH * len(VARIANTS)), (0, 0, 0, 0))
    out_hair = Image.new("L", (FW * total_cols, FH * len(VARIANTS)), 0)
    out_clothing = Image.new("L", (FW * total_cols, FH * len(VARIANTS)), 0)

    for gi, (prefix, gender, role) in enumerate(VARIANTS):
        sheet = Image.open(SRC / f"{prefix}_spritesheet.png").convert("RGBA")
        hair_mask = Image.open(SRC / f"{prefix}_hair_mask.png").convert("L")
        clothing_mask = Image.open(SRC / f"{prefix}_clothing_mask.png").convert("L")
        # ขยายมาสก์ 1px (dilate) — ต้นฉบับตัดมาสก์เฉพาะพื้นที่ทึบ ไม่รวมเส้นขอบ/เงาโทนเข้มรอบ ๆ
        # (ซึ่งมักเป็นสีเดิมเข้มลง ไม่ใช่สีดำล้วน) พอ recolor เป็นสีที่ต่างจากเดิมมาก ๆ เลยเหลือ
        # ริมสีเดิมเป็นขอบบาง ๆ ให้เห็น — ขยายมาสก์ให้คลุมเส้นขอบนั้นด้วยเลย
        hair_mask = hair_mask.filter(ImageFilter.MaxFilter(3))
        clothing_mask = clothing_mask.filter(ImageFilter.MaxFilter(3))
        # เผื่อ dilate ทำให้มาสก์ผมกับเสื้อมาชนกัน (เช่น ปอยผมย้อยใกล้โบว์ปกเสื้อ) — ต้องกันไม่ให้
        # พิกเซลเดียวอยู่ในสองมาสก์พร้อมกัน ไม่งั้นตอน recolor ฝั่งที่รันทีหลัง (เสื้อ) จะทับสีผมทิ้ง
        # เงียบ ๆ (เห็นเป็นสีเสื้อเพี้ยนไปโผล่กลางทรงผม) — พิกเซลที่ชนกันตัดทิ้งจากทั้งสองมาสก์เลย
        overlap = ImageChops.darker(hair_mask, clothing_mask)
        hair_mask = ImageChops.subtract(hair_mask, overlap)
        clothing_mask = ImageChops.subtract(clothing_mask, overlap)

        for gdi, src_row in enumerate(SRC_ROW_FOR_GAME_DIR):
            for col in range(SRC_COLS):
                box = (col * SRC_FRAME, src_row * SRC_FRAME, (col + 1) * SRC_FRAME, (src_row + 1) * SRC_FRAME)
                frame = sheet.crop(box)
                bbox = content_bbox(frame)
                if not bbox:
                    continue
                # ใช้ bbox เดียวกัน (คำนวณจากช่องอัลฟาของภาพสี) ตัดทั้งภาพสีและมาสก์ ให้พิกเซลตรงกันเป๊ะ
                frame_cropped = frame.crop(bbox)
                hair_cropped = drop_small_components(hair_mask.crop(box).crop(bbox))
                clothing_cropped = drop_small_components(clothing_mask.crop(box).crop(bbox))

                placed_frame = place(frame_cropped, scale, "RGBA")
                placed_hair = rebinarize_mask(place(hair_cropped, scale, "L"))
                placed_clothing = rebinarize_mask(place(clothing_cropped, scale, "L"))

                dst_x = (gdi * SRC_COLS + col) * FW
                bob = BOB_PATTERN[col] if gdi in (0, 3) else 0
                dst_y = gi * FH + bob
                out_sheet.alpha_composite(placed_frame, (dst_x, dst_y))
                out_hair.paste(placed_hair, (dst_x, dst_y))
                out_clothing.paste(placed_clothing, (dst_x, dst_y))

    out_sheet.save(OUT / "avatars.png")
    out_hair.save(OUT / "avatars_hair_mask.png")
    out_clothing.save(OUT / "avatars_clothing_mask.png")

    meta = {
        "frameW": FW, "frameH": FH, "dirs": GAME_DIRS, "frames": SRC_COLS,
        "hairMask": "avatars_hair_mask.png", "clothingMask": "avatars_clothing_mask.png",
        "variants": [{"gender": gender, "role": role} for _, gender, role in VARIANTS],
    }
    (OUT / "avatars.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"wrote avatars.png {out_sheet.size[0]}x{out_sheet.size[1]} + masks + avatars.json")


if __name__ == "__main__":
    build()
